# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base:

active_record_encryption:
  primary_key:
  deterministic_key:
  key_derivation_salt:

openai:
  api_key:
  org_id:

pinecone:
  api_key:
  cloud:
  region:

aws:
  access_key_id:
  secret_access_key:

stripe:
  publishable_key:
  secret_key:
  webhook_secret:

twilio:
  account_sid:
  auth_token:
  verify_sid:

vital:
  api_base_url:
  api_key:
  webhook_secret:

amplitude:
  api_key:
  api_base_url:

jwt_secret:

apple:
  app_bundle_id:
  public_keys_url:

domain: localhost
