module AppleHealth
  extend ActiveSupport::Concern

  included do
    def map_apple_health_quantity_type(type)
      types = {
        # Currently being used
        HKQuantityTypeIdentifierStepCount: 'Step Count',
        HKQuantityTypeIdentifierBodyFatPercentage: 'Body Fat Percentage',
        HKQuantityTypeIdentifierBodyMass: 'Body Mass',
        HKQuantityTypeIdentifierBodyMassIndex: 'Body Mass Index',
        HKQuantityTypeIdentifierHeight: 'Height',
        HKQuantityTypeIdentifierHeartRate: 'Heart Rate',
        HKQuantityTypeIdentifierHeartRateVariabilitySDNN: 'Heart Rate Variability',
        HKQuantityTypeIdentifierRestingHeartRate: 'Resting Heart Rate',
        HKQuantityTypeIdentifierVO2Max: 'VO2 Max',
        HKQuantityTypeIdentifierBloodPressureDiastolic: 'Blood Pressure Diastolic',
        HKQuantityTypeIdentifierBloodPressureSystolic: 'Blood Pressure Systolic',
        HKQuantityTypeIdentifierRespiratoryRate: 'Respiratory Rate',
        HKQuantityTypeIdentifierBloodGlucose: 'Blood Glucose',
        # Not being used
        HKQuantityTypeIdentifierLeanBodyMass: 'Lean Body Mass',
        HKQuantityTypeIdentifierWaistCircumference: 'Waist Circumference',
        HKQuantityTypeIdentifierDistanceWalkingRunning: 'Distance Walking Running',
        HKQuantityTypeIdentifierDistanceCycling: 'Distance Cycling',
        HKQuantityTypeIdentifierDistanceWheelchair: 'Distance Wheelchair',
        HKQuantityTypeIdentifierBasalEnergyBurned: 'Basal Energy Burned',
        HKQuantityTypeIdentifierActiveEnergyBurned: 'Active Energy Burned',
        HKQuantityTypeIdentifierFlightsClimbed: 'Flights Climbed',
        HKQuantityTypeIdentifierNikeFuel: 'Nike Fuel',
        HKQuantityTypeIdentifierAppleExerciseTime: 'Apple Exercise Time',
        HKQuantityTypeIdentifierPushCount: 'Push Count',
        HKQuantityTypeIdentifierDistanceSwimming: 'Distance Swimming',
        HKQuantityTypeIdentifierSwimmingStrokeCount: 'Swimming Stroke Count',
        HKQuantityTypeIdentifierDistanceDownhillSnowSports: 'Distance Downhill Snow Sports',
        HKQuantityTypeIdentifierAppleStandTime: 'Apple Stand Time',
        HKQuantityTypeIdentifierBodyTemperature: 'Body Temperature',
        HKQuantityTypeIdentifierBasalBodyTemperature: 'Basal Body Temperature',
        HKQuantityTypeIdentifierWalkingHeartRateAverage: 'Walking Heart Rate Average',
        HKQuantityTypeIdentifierOxygenSaturation: 'Oxygen Saturation',
        HKQuantityTypeIdentifierPeripheralPerfusionIndex: 'Peripheral Perfusion Index',
        HKQuantityTypeIdentifierNumberOfTimesFallen: 'Number Of Times Fallen',
        HKQuantityTypeIdentifierElectrodermalActivity: 'Electrodermal Activity',
        HKQuantityTypeIdentifierInhalerUsage: 'Inhaler Usage',
        HKQuantityTypeIdentifierInsulinDelivery: 'Insulin Delivery',
        HKQuantityTypeIdentifierBloodAlcoholContent: 'Blood Alcohol Content',
        HKQuantityTypeIdentifierForcedVitalCapacity: 'Forced Vital Capacity',
        HKQuantityTypeIdentifierForcedExpiratoryVolume1: 'Forced Expiratory Volume 1',
        HKQuantityTypeIdentifierPeakExpiratoryFlowRate: 'Peak Expiratory Flow Rate',
        HKQuantityTypeIdentifierEnvironmentalAudioExposure: 'Environmental Audio Exposure',
        HKQuantityTypeIdentifierHeadphoneAudioExposure: 'Headphone Audio Exposure',
        HKQuantityTypeIdentifierDietaryFatTotal: 'Dietary Fat Total',
        HKQuantityTypeIdentifierDietaryFatPolyunsaturated: 'Dietary Fat Polyunsaturated',
        HKQuantityTypeIdentifierDietaryFatMonounsaturated: 'Dietary Fat Monounsaturated',
        HKQuantityTypeIdentifierDietaryFatSaturated: 'Dietary Fat Saturated',
        HKQuantityTypeIdentifierDietaryCholesterol: 'Dietary Cholesterol',
        HKQuantityTypeIdentifierDietarySodium: 'Dietary Sodium',
        HKQuantityTypeIdentifierDietaryCarbohydrates: 'Dietary Carbohydrates',
        HKQuantityTypeIdentifierDietaryFiber: 'Dietary Fiber',
        HKQuantityTypeIdentifierDietarySugar: 'Dietary Sugar',
        HKQuantityTypeIdentifierDietaryEnergyConsumed: 'Dietary Energy Consumed',
        HKQuantityTypeIdentifierDietaryProtein: 'Dietary Protein',
        HKQuantityTypeIdentifierDietaryVitaminA: 'Dietary Vitamin A',
        HKQuantityTypeIdentifierDietaryVitaminB6: 'Dietary Vitamin B6',
        HKQuantityTypeIdentifierDietaryVitaminB12: 'Dietary Vitamin B12',
        HKQuantityTypeIdentifierDietaryVitaminC: 'Dietary Vitamin C',
        HKQuantityTypeIdentifierDietaryVitaminD: 'Dietary Vitamin D',
        HKQuantityTypeIdentifierDietaryVitaminE: 'Dietary Vitamin E',
        HKQuantityTypeIdentifierDietaryVitaminK: 'Dietary Vitamin K',
        HKQuantityTypeIdentifierDietaryCalcium: 'Dietary Calcium',
        HKQuantityTypeIdentifierDietaryIron: 'Dietary Iron',
        HKQuantityTypeIdentifierDietaryThiamin: 'Dietary Thiamin',
        HKQuantityTypeIdentifierDietaryRiboflavin: 'Dietary Riboflavin',
        HKQuantityTypeIdentifierDietaryNiacin: 'Dietary Niacin',
        HKQuantityTypeIdentifierDietaryFolate: 'Dietary Folate',
        HKQuantityTypeIdentifierDietaryBiotin: 'Dietary Biotin',
        HKQuantityTypeIdentifierDietaryPantothenicAcid: 'Dietary Pantothenic Acid',
        HKQuantityTypeIdentifierDietaryPhosphorus: 'Dietary Phosphorus',
        HKQuantityTypeIdentifierDietaryIodine: 'Dietary Iodine',
        HKQuantityTypeIdentifierDietaryMagnesium: 'Dietary Magnesium',
        HKQuantityTypeIdentifierDietaryZinc: 'Dietary Zinc',
        HKQuantityTypeIdentifierDietarySelenium: 'Dietary Selenium',
        HKQuantityTypeIdentifierDietaryCopper: 'Dietary Copper',
        HKQuantityTypeIdentifierDietaryManganese: 'Dietary Manganese',
        HKQuantityTypeIdentifierDietaryChromium: 'Dietary Chromium',
        HKQuantityTypeIdentifierDietaryMolybdenum: 'Dietary Molybdenum',
        HKQuantityTypeIdentifierDietaryChloride: 'Dietary Chloride',
        HKQuantityTypeIdentifierDietaryPotassium: 'Dietary Potassium',
        HKQuantityTypeIdentifierDietaryCaffeine: 'Dietary Caffeine',
        HKQuantityTypeIdentifierDietaryWater: 'Dietary Water',
        HKQuantityTypeIdentifierSixMinuteWalkTestDistance: 'Six Minute Walk Test Distance',
        HKQuantityTypeIdentifierWalkingSpeed: 'Walking Speed',
        HKQuantityTypeIdentifierWalkingStepLength: 'Walking Step Length',
        HKQuantityTypeIdentifierWalkingAsymmetryPercentage: 'Walking Asymmetry Percentage',
        HKQuantityTypeIdentifierWalkingDoubleSupportPercentage: 'Walking Double Support Percentage',
        HKQuantityTypeIdentifierStairAscentSpeed: 'Stair Ascent Speed',
        HKQuantityTypeIdentifierStairDescentSpeed: 'Stair Descent Speed',
        HKQuantityTypeIdentifierUVExposure: 'UV Exposure',
        HKQuantityTypeIdentifierAppleMoveTime: 'Apple Move Time',
        HKQuantityTypeIdentifierAppleWalkingSteadiness: 'Apple Walking Steadiness',
        HKQuantityTypeIdentifierNumberOfAlcoholicBeverages: 'Number Of Alcoholic Beverages',
        HKQuantityTypeIdentifierAtrialFibrillationBurden: 'Atrial Fibrillation Burden',
        HKQuantityTypeIdentifierUnderwaterDepth: 'Underwater Depth',
        HKQuantityTypeIdentifierWaterTemperature: 'Water Temperature',
        HKQuantityTypeIdentifierAppleSleepingWristTemperature: 'Apple Sleeping Wrist Temperature',
        HKQuantityTypeIdentifierTimeInDaylight: 'Time In Daylight',
        HKQuantityTypeIdentifierPhysicalEffort: 'Physical Effort',
        HKQuantityTypeIdentifierCyclingSpeed: 'Cycling Speed',
        HKQuantityTypeIdentifierCyclingPower: 'Cycling Power',
        HKQuantityTypeIdentifierCyclingFunctionalThresholdPower: 'Cycling Functional Threshold Power',
        HKQuantityTypeIdentifierCyclingCadence: 'Cycling Cadence',
        HKQuantityTypeIdentifierEnvironmentalSoundReduction: 'Environmental Sound Reduction',
        HKQuantityTypeIdentifierHeartRateRecoveryOneMinute: 'Heart Rate Recovery One Minute',
        HKQuantityTypeIdentifierRunningGroundContactTime: 'Running Ground Contact Time',
        HKQuantityTypeIdentifierRunningStrideLength: 'Running Stride Length',
        HKQuantityTypeIdentifierRunningPower: 'Running Power',
        HKQuantityTypeIdentifierRunningVerticalOscillation: 'Running Vertical Oscillation',
        HKQuantityTypeIdentifierRunningSpeed: 'Running Speed'
      }
      if types[type.to_sym].present?
        types[type.to_sym]
      else
        type
      end
    end

    def map_apple_health_category_type(type)
      types = {
        # Currently being used
        HKCategoryTypeIdentifierSleepAnalysis: 'Sleep Analysis',
        # Not being used
        HKCategoryTypeIdentifierAppleStandHour: 'Apple Stand Hour',
        HKCategoryTypeIdentifierCervicalMucusQuality: 'Cervical Mucus Quality',
        HKCategoryTypeIdentifierOvulationTestResult: 'Ovulation Test Result',
        HKCategoryTypeIdentifierMenstrualFlow: 'Menstrual Flow',
        HKCategoryTypeIdentifierIntermenstrualBleeding: 'Intermenstrual Bleeding',
        HKCategoryTypeIdentifierSexualActivity: 'Sexual Activity',
        HKCategoryTypeIdentifierMindfulSession: 'Mindful Session',
        HKCategoryTypeIdentifierHighHeartRateEvent: 'High Heart Rate Event',
        HKCategoryTypeIdentifierLowHeartRateEvent: 'Low Heart Rate Event',
        HKCategoryTypeIdentifierIrregularHeartRhythmEvent: 'Irregular Heart Rhythm Event',
        HKCategoryTypeIdentifierToothbrushingEvent: 'Toothbrushing Event',
        HKCategoryTypeIdentifierLowCardioFitnessEvent: 'Low Cardio Fitness Event',
        HKCategoryTypeIdentifierContraceptive: 'Contraceptive',
        HKCategoryTypeIdentifierLactation: 'Lactation',
        HKCategoryTypeIdentifierPregnancy: 'Pregnancy',
        HKCategoryTypeIdentifierPregnancyTestResult: 'Pregnancy Test Result',
        HKCategoryTypeIdentifierProgesteroneTestResult: 'Progesterone Test Result',
        HKCategoryTypeIdentifierEnvironmentalAudioExposureEvent: 'Environmental Audio Exposure Event',
        HKCategoryTypeIdentifierHeadphoneAudioExposureEvent: 'Headphone Audio Exposure Event',
        HKCategoryTypeIdentifierAppleWalkingSteadinessEvent: 'Apple Walking Steadiness Event',
        HKCategoryTypeIdentifierHandwashingEvent: 'Handwashing Event',
        HKCategoryTypeIdentifierAbdominalCramps: 'Abdominal Cramps',
        HKCategoryTypeIdentifierAcne: 'Acne',
        HKCategoryTypeIdentifierAppetiteChanges: 'Appetite Changes',
        HKCategoryTypeIdentifierBladderIncontinence: 'Bladder Incontinence',
        HKCategoryTypeIdentifierBloating: 'Bloating',
        HKCategoryTypeIdentifierBreastPain: 'Breast Pain',
        HKCategoryTypeIdentifierChestTightnessOrPain: 'Chest Tightness Or Pain',
        HKCategoryTypeIdentifierChills: 'Chills',
        HKCategoryTypeIdentifierConstipation: 'Constipation',
        HKCategoryTypeIdentifierCoughing: 'Coughing',
        HKCategoryTypeIdentifierDiarrhea: 'Diarrhea',
        HKCategoryTypeIdentifierDizziness: 'Dizziness',
        HKCategoryTypeIdentifierDrySkin: 'Dry Skin',
        HKCategoryTypeIdentifierFainting: 'Fainting',
        HKCategoryTypeIdentifierFatigue: 'Fatigue',
        HKCategoryTypeIdentifierFever: 'Fever',
        HKCategoryTypeIdentifierGeneralizedBodyAche: 'Generalized Body Ache',
        HKCategoryTypeIdentifierHairLoss: 'Hair Loss',
        HKCategoryTypeIdentifierHeadache: 'Headache',
        HKCategoryTypeIdentifierHeartburn: 'Heartburn',
        HKCategoryTypeIdentifierHotFlashes: 'Hot Flashes',
        HKCategoryTypeIdentifierLossOfSmell: 'Loss Of Smell',
        HKCategoryTypeIdentifierLossOfTaste: 'Loss Of Taste',
        HKCategoryTypeIdentifierLowerBackPain: 'Lower Back Pain',
        HKCategoryTypeIdentifierMemoryLapse: 'Memory Lapse',
        HKCategoryTypeIdentifierMoodChanges: 'Mood Changes',
        HKCategoryTypeIdentifierNausea: 'Nausea',
        HKCategoryTypeIdentifierNightSweats: 'Night Sweats',
        HKCategoryTypeIdentifierPelvicPain: 'Pelvic Pain',
        HKCategoryTypeIdentifierRapidPoundingOrFlutteringHeartbeat:
          'Rapid Pounding Or Fluttering Heartbeat',
        HKCategoryTypeIdentifierRunnyNose: 'Runny Nose',
        HKCategoryTypeIdentifierShortnessOfBreath: 'Shortness Of Breath',
        HKCategoryTypeIdentifierSinusCongestion: 'Sinus Congestion',
        HKCategoryTypeIdentifierSkippedHeartbeat: 'Skipped Heartbeat',
        HKCategoryTypeIdentifierSleepChanges: 'Sleep Changes',
        HKCategoryTypeIdentifierSoreThroat: 'Sore Throat',
        HKCategoryTypeIdentifierVaginalDryness: 'Vaginal Dryness',
        HKCategoryTypeIdentifierVomiting: 'Vomiting',
        HKCategoryTypeIdentifierWheezing: 'Wheezing'
      }
      if types[type.to_sym].present?
        types[type.to_sym]
      else
        type
      end
    end

    def map_apple_health_category_value(type, value)
      values = {
        HKCategoryTypeIdentifierHandwashingEvent: {
          0 => 'Not Applicable'
        },
        HKCategoryTypeIdentifierSleepAnalysis: {
          0 => 'In Bed',
          1 => 'Asleep (Unspecified)',
          2 => 'Awake',
          3 => 'Core',
          4 => 'Deep',
          5 => 'REM',
        },
        HKCategoryTypeIdentifierAppleStandHour: {
          0 => 'Stood',
          1 => 'Idle',
        },
        HKCategoryTypeIdentifierCervicalMucusQuality: {
          1 => 'Dry',
          2 => 'Sticky',
          3 => 'Creamy',
          4 => 'Watery',
          5 => 'Egg White',
        },
        HKCategoryTypeIdentifierOvulationTestResult: {
          1 => 'Negative',
          2 => 'Positive',
          3 => 'Indeterminate',
          4 => 'Estrogen Surge',
        },
        HKCategoryTypeIdentifierMenstrualFlow: {
          1 => 'Unspecified',
          2 => 'Light',
          3 => 'Medium',
          4 => 'Heavy',
          5 => 'None',
        },
        HKCategoryTypeIdentifierHighHeartRateEvent: {
          0 => 'Not Applicable',
        },
        HKCategoryTypeIdentifierIntermenstrualBleeding: {
          0 => 'Not Applicable',
        },
        HKCategoryTypeIdentifierMindfulSession: {
          0 => 'Not Applicable',
        },
        HKCategoryTypeIdentifierSexualActivity: {
          0 => 'Not Applicable',
        },
        HKCategoryTypeIdentifierLowCardioFitnessEvent: {
          1 => 'Low Fitness',
        },
        HKCategoryTypeIdentifierPregnancyTestResult: {
          1 => 'Negative',
          2 => 'Positive',
          3 => 'Indeterminate',
        },
        HKCategoryTypeIdentifierAbdominalCramps: {
          0 => 'Unspecified',
          1 => 'Not Present',
          2 => 'Mild',
          3 => 'Moderate',
          4 => 'Severe',
        },
        HKCategoryTypeIdentifierAcne: {
          0 => 'Unspecified',
          1 => 'Not Present',
          2 => 'Mild',
          3 => 'Moderate',
          4 => 'Severe',
        },
        HKCategoryTypeIdentifierAppetiteChanges: {
          0 => 'Present',
          1 => 'Not Present',
        },
        HKCategoryTypeIdentifierBladderIncontinence: {
          0 => 'Unspecified',
          1 => 'Not Present',
          2 => 'Mild',
          3 => 'Moderate',
          4 => 'Severe',
        },
        HKCategoryTypeIdentifierBloating: {
          0 => 'Unspecified',
          1 => 'Not Present',
          2 => 'Mild',
          3 => 'Moderate',
          4 => 'Severe',
        },
        HKCategoryTypeIdentifierBreastPain: {
          0 => 'Unspecified',
          1 => 'Not Present',
          2 => 'Mild',
          3 => 'Moderate',
          4 => 'Severe',
        },
        HKCategoryTypeIdentifierChestTightnessOrPain: {
          0 => 'Unspecified',
          1 => 'Not Present',
          2 => 'Mild',
          3 => 'Moderate',
          4 => 'Severe',
        },
        HKCategoryTypeIdentifierChills: {
          0 => 'Unspecified',
          1 => 'Not Present',
          2 => 'Mild',
          3 => 'Moderate',
          4 => 'Severe',
        },
        HKCategoryTypeIdentifierConstipation: {
          0 => 'Unspecified',
          1 => 'Not Present',
          2 => 'Mild',
          3 => 'Moderate',
          4 => 'Severe',
        },
        HKCategoryTypeIdentifierCoughing: {
          0 => 'Unspecified',
          1 => 'Not Present',
          2 => 'Mild',
          3 => 'Moderate',
          4 => 'Severe',
        },
        HKCategoryTypeIdentifierDiarrhea: {
          0 => 'Unspecified',
          1 => 'Not Present',
          2 => 'Mild',
          3 => 'Moderate',
          4 => 'Severe',
        },
        HKCategoryTypeIdentifierDizziness: {
          0 => 'Unspecified',
          1 => 'Not Present',
          2 => 'Mild',
          3 => 'Moderate',
          4 => 'Severe',
        },
        HKCategoryTypeIdentifierDrySkin: {
          0 => 'Unspecified',
          1 => 'Not Present',
          2 => 'Mild',
          3 => 'Moderate',
          4 => 'Severe',
        },
        HKCategoryTypeIdentifierFainting: {
          0 => 'Unspecified',
          1 => 'Not Present',
          2 => 'Mild',
          3 => 'Moderate',
          4 => 'Severe',
        },
        HKCategoryTypeIdentifierFatigue: {
          0 => 'Unspecified',
          1 => 'Not Present',
          2 => 'Mild',
          3 => 'Moderate',
          4 => 'Severe',
        },
        HKCategoryTypeIdentifierFever: {
          0 => 'Unspecified',
          1 => 'Not Present',
          2 => 'Mild',
          3 => 'Moderate',
          4 => 'Severe',
        },
        HKCategoryTypeIdentifierGeneralizedBodyAche: {
          0 => 'Unspecified',
          1 => 'Not Present',
          2 => 'Mild',
          3 => 'Moderate',
          4 => 'Severe',
        },
        HKCategoryTypeIdentifierHairLoss: {
          0 => 'Unspecified',
          1 => 'Not Present',
          2 => 'Mild',
          3 => 'Moderate',
          4 => 'Severe',
        },
        HKCategoryTypeIdentifierHeadache: {
          0 => 'Unspecified',
          1 => 'Not Present',
          2 => 'Mild',
          3 => 'Moderate',
          4 => 'Severe',
        },
        HKCategoryTypeIdentifierHeartburn: {
          0 => 'Unspecified',
          1 => 'Not Present',
          2 => 'Mild',
          3 => 'Moderate',
          4 => 'Severe',
        },
        HKCategoryTypeIdentifierHotFlashes: {
          0 => 'Unspecified',
          1 => 'Not Present',
          2 => 'Mild',
          3 => 'Moderate',
          4 => 'Severe',
        },
        HKCategoryTypeIdentifierLossOfSmell: {
          0 => 'Unspecified',
          1 => 'Not Present',
          2 => 'Mild',
          3 => 'Moderate',
          4 => 'Severe',
        },
        HKCategoryTypeIdentifierLossOfTaste: {
          0 => 'Unspecified',
          1 => 'Not Present',
          2 => 'Mild',
          3 => 'Moderate',
          4 => 'Severe',
        },
        HKCategoryTypeIdentifierLowerBackPain: {
          0 => 'Unspecified',
          1 => 'Not Present',
          2 => 'Mild',
          3 => 'Moderate',
          4 => 'Severe',
        },
        HKCategoryTypeIdentifierMemoryLapse: {
          0 => 'Unspecified',
          1 => 'Not Present',
          2 => 'Mild',
          3 => 'Moderate',
          4 => 'Severe',
        },
        HKCategoryTypeIdentifierMoodChanges: {
          0 => 'Unspecified',
          1 => 'Not Present',
          2 => 'Mild',
          3 => 'Moderate',
          4 => 'Severe',
        },
        HKCategoryTypeIdentifierNausea: {
          0 => 'Unspecified',
          1 => 'Not Present',
          2 => 'Mild',
          3 => 'Moderate',
          4 => 'Severe',
        },
        HKCategoryTypeIdentifierNightSweats: {
          0 => 'Unspecified',
          1 => 'Not Present',
          2 => 'Mild',
          3 => 'Moderate',
          4 => 'Severe',
        },
        HKCategoryTypeIdentifierPelvicPain: {
          0 => 'Unspecified',
          1 => 'Not Present',
          2 => 'Mild',
          3 => 'Moderate',
          4 => 'Severe',
        },
        HKCategoryTypeIdentifierRapidPoundingOrFlutteringHeartbeat: {
          0 => 'Unspecified',
          1 => 'Not Present',
          2 => 'Mild',
          3 => 'Moderate',
          4 => 'Severe',
        },
        HKCategoryTypeIdentifierRunnyNose: {
          0 => 'Unspecified',
          1 => 'Not Present',
          2 => 'Mild',
          3 => 'Moderate',
          4 => 'Severe',
        },
        HKCategoryTypeIdentifierShortnessOfBreath: {
          0 => 'Unspecified',
          1 => 'Not Present',
          2 => 'Mild',
          3 => 'Moderate',
          4 => 'Severe',
        },
        HKCategoryTypeIdentifierSinusCongestion: {
          0 => 'Unspecified',
          1 => 'Not Present',
          2 => 'Mild',
          3 => 'Moderate',
          4 => 'Severe',
        },
        HKCategoryTypeIdentifierSkippedHeartbeat: {
          0 => 'Unspecified',
          1 => 'Not Present',
          2 => 'Mild',
          3 => 'Moderate',
          4 => 'Severe',
        },
        HKCategoryTypeIdentifierSleepChanges: {
          0 => 'Present',
          1 => 'Not Present',
        },
        HKCategoryTypeIdentifierSoreThroat: {
          0 => 'Unspecified',
          1 => 'Not Present',
          2 => 'Mild',
          3 => 'Moderate',
          4 => 'Severe',
        },
        HKCategoryTypeIdentifierVaginalDryness: {
          0 => 'Unspecified',
          1 => 'Not Present',
          2 => 'Mild',
          3 => 'Moderate',
          4 => 'Severe',
        },
        HKCategoryTypeIdentifierVomiting: {
          0 => 'Unspecified',
          1 => 'Not Present',
          2 => 'Mild',
          3 => 'Moderate',
          4 => 'Severe',
        },
        HKCategoryTypeIdentifierWheezing: {
          0 => 'Unspecified',
          1 => 'Not Present',
          2 => 'Mild',
          3 => 'Moderate',
          4 => 'Severe',
        }
      }
      if values[type.to_sym].present?
        values[type.to_sym][value]
      else
        value.to_s
      end
    end

    def map_apple_health_clinical_type(type)
      types = {
        HKClinicalTypeIdentifierAllergyRecord: 'Allergy',
        HKClinicalTypeIdentifierClinicalNoteRecord: 'Clinical Note',
        HKClinicalTypeIdentifierConditionRecord: 'Condition',
        HKClinicalTypeIdentifierCoverageRecord: 'Insurance',
        HKClinicalTypeIdentifierImmunizationRecord: 'Immunization',
        HKClinicalTypeIdentifierLabResultRecord: 'Lab Result',
        HKClinicalTypeIdentifierMedicationRecord: 'Medication',
        HKClinicalTypeIdentifierProcedureRecord: 'Procedure',
        HKClinicalTypeIdentifierVitalSignRecord: 'Vital Sign',
      }
      if types[type.to_sym].present?
        types[type.to_sym]
      else
        type
      end
    end

    def map_apple_health_workout_activity_type(type)
      types = {
        1 =>'americanFootball',
        2 =>'archery',
        3 =>'australianFootball',
        4 =>'badminton',
        5 =>'baseball',
        6 =>'basketball',
        7 =>'bowling',
        8 =>'boxing',
        9 =>'climbing',
        10 =>'cricket',
        11 =>'crossTraining',
        12 =>'curling',
        13 =>'cycling',
        14 =>'dance',
        15 =>'danceInspiredTraining',
        16 =>'elliptical',
        17 =>'equestrianSports',
        18 =>'fencing',
        19 =>'fishing',
        20 =>'functionalStrengthTraining',
        21 =>'golf',
        22 =>'gymnastics',
        23 =>'handball',
        24 =>'hiking',
        25 =>'hockey',
        26 =>'hunting',
        27 =>'lacrosse',
        28 =>'martialArts',
        29 =>'mindAndBody',
        30 =>'mixedMetabolicCardioTraining',
        31 =>'paddleSports',
        32 =>'play',
        33 =>'preparationAndRecovery',
        34 =>'racquetball',
        35 =>'rowing',
        36 =>'rugby',
        37 =>'running',
        38 =>'sailing',
        39 =>'skatingSports',
        40 =>'snowSports',
        41 =>'soccer',
        42 =>'softball',
        43 =>'squash',
        44 =>'stairClimbing',
        45 =>'surfingSports',
        46 =>'swimming',
        47 =>'tableTennis',
        48 =>'tennis',
        49 =>'trackAndField',
        50 =>'traditionalStrengthTraining',
        51 =>'volleyball',
        52 =>'walking',
        53 =>'waterFitness',
        54 =>'waterPolo',
        55 =>'waterSports',
        56 =>'wrestling',
        57 =>'yoga',
        58 =>'barre',
        59 =>'coreTraining',
        60 =>'crossCountrySkiing',
        61 =>'downhillSkiing',
        62 =>'flexibility',
        63 =>'highIntensityIntervalTraining',
        64 =>'jumpRope',
        65 =>'kickboxing',
        66 =>'pilates',
        67 =>'snowboarding',
        68 =>'stairs',
        69 =>'stepTraining',
        70 =>'wheelchairWalkPace',
        71 =>'wheelchairRunPace',
        72 =>'taiChi',
        73 =>'mixedCardio',
        74 =>'handCycling',
        75 =>'discSports',
        76 =>'fitnessGaming',
        77 =>'cardioDance',
        78 =>'socialDance',
        79 =>'pickleball',
        80 =>'cooldown',
        82 =>'swimBikeRun',
        83 =>'transition',
        84 =>'underwaterDiving',
        3000 =>'other',
      }
      if types[type].present?
        types[type]
      else
        type.to_s
      end
    end
  end
end